blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/BrennonTWilliams/dotfiles/blob/main/README.md
    about: Please check the documentation first
  - name: Discussions
    url: https://github.com/BrennonTWilliams/dotfiles/discussions
    about: Ask questions and discuss ideas
